#!/bin/sh

sudo pacman -Syu --noconfirm

function install {
  if pacman -Qi $1 &> /dev/null; then
    echo "Already installed: ${1}"
  else
    if yay -Qi $1 &> /dev/null; then
      echo "Already installed: ${1}"
    else
      echo "Installing using yay: ${1}..."
      yay -S --noconfirm $1
    fi
  fi
}

install gnome-mines
install kpat
install emacs
install keepassxc
install flameshot
install firefox
install irssi
install mpv
install feh
install kigo
install kreversi
install neovim
install kmahjongg
install i3
install gdb
install codeblocks
install artha

